INSERT INTO tb_category (name) VALUES
    ('Fashion Accessories'),
    ('Home Decor'),
    ('Mobile Phones and Accessories'),
    ('Gourmet Food'),
    ('Outdoor Recreation'),
    ('Personal Electronics'),
    ('Kitchen Appliances'),
    ('Books and Magazines'),
    ('Musical Instruments'),
    ('Automotive Parts and Accessories'),
    ('Fine Jewelry'),
    ('School and Educational Supplies'),
    ('Pet Food'),
    ('Video Games'),
    ('Health and Fitness'),
    ('Home Improvement'),
    ('Party Supplies'),
    ('Hand Tools'),
    ('Writing Instruments'),
    ('Luggage and Travel Gear'),
    ('Pet Care'),
    ('Digital Music'),
    ('Movies and DVDs'),
    ('Baby Clothing'),
    ('Gardening Supplies'),
    ('Craft Supplies'),
    ('Baby Gear'),
    ('Sports Equipment'),
    ('Electronics'),
    ('Clothing'),
    ('Books'),
    ('Home and Kitchen'),
    ('Sports and Outdoors'),
    ('Beauty and Personal Care'),
    ('Toys and Games'),
    ('Health and Wellness'),
    ('Furniture'),
    ('Automotive'),
    ('Jewelry'),
    ('Office Supplies'),
    ('Pet Supplies'),
    ('Music'),
    ('Movies and TV Shows'),
    ('Groceries'),
    ('Fitness and Exercise'),
    ('Electrical Appliances'),
    ('Garden and Outdoor'),
    ('Art and Craft'),
    ('Baby Products'),
    ('Party and Celebration'),
    ('Tools and Hardware'),
    ('Stationery'),
    ('Travel and Luggage');


INSERT INTO tb_product (name, description, price, img_url) VALUES
    ('Smartphone', 'High-end smartphone with advanced features.', 799.99, 'https://example.com/smartphone.jpg'),
    ('Laptop', 'Powerful laptop for productivity and gaming.', 1299.99, 'https://example.com/laptop.jpg'),
    ('Wireless Earbuds', 'Bluetooth earbuds with noise cancellation.', 99.99, 'https://example.com/earbuds.jpg'),
    ('LED TV', 'Large LED TV with 4K resolution.', 899.99, 'https://example.com/tv.jpg'),
    ('Digital Camera', 'Mirrorless camera with 24MP sensor.', 699.99, 'https://example.com/camera.jpg'),
    ('Fitness Tracker', 'Waterproof fitness tracker with heart rate monitor.', 49.99, 'https://example.com/fitness-tracker.jpg'),
    ('Gaming Console', 'Latest gaming console with a large game library.', 399.99, 'https://example.com/gaming-console.jpg'),
    ('Smart Watch', 'Smartwatch with various health and fitness features.', 149.99, 'https://example.com/smart-watch.jpg'),
    ('Bluetooth Speaker', 'Portable Bluetooth speaker with excellent sound quality.', 79.99, 'https://example.com/speaker.jpg'),
    ('Tablet', 'High-performance tablet with a large display.', 299.99, 'https://example.com/tablet.jpg'),
    ('Headphones', 'Over-ear headphones with active noise cancellation.', 149.99, 'https://example.com/headphones.jpg'),
    ('External Hard Drive', 'External HDD with a capacity of 2TB.', 89.99, 'https://example.com/hdd.jpg'),
    ('Wireless Mouse', 'Ergonomic wireless mouse for comfortable use.', 29.99, 'https://example.com/mouse.jpg'),
    ('Gaming Keyboard', 'Mechanical gaming keyboard with customizable RGB lighting.', 129.99, 'https://example.com/keyboard.jpg'),
    ('Power Bank', 'High-capacity power bank for charging devices on the go.', 49.99, 'https://example.com/power-bank.jpg'),
    ('Portable SSD', 'Fast and compact portable SSD with 500GB storage.', 159.99, 'https://example.com/ssd.jpg'),
    ('Smart Thermostat', 'Wi-Fi enabled smart thermostat for home automation.', 129.99, 'https://example.com/thermostat.jpg'),
    ('Electric Toothbrush', 'Electric toothbrush for efficient oral care.', 39.99, 'https://example.com/toothbrush.jpg'),
    ('Robot Vacuum Cleaner', 'Robotic vacuum cleaner with intelligent mapping.', 299.99, 'https://example.com/robot-vacuum.jpg'),
    ('Wireless Router', 'High-speed wireless router for seamless internet connectivity.', 79.99, 'https://example.com/router.jpg'),
    ('Sneakers', 'Stylish and comfortable sneakers for daily wear.', 79.99, 'https://example.com/sneakers.jpg'),
    ('Graphic T-Shirt', 'Cotton graphic t-shirt with unique design.', 19.99, 'https://example.com/graphic-tshirt.jpg'),
    ('Denim Jeans', 'Classic denim jeans for a casual look.', 49.99, 'https://example.com/jeans.jpg'),
    ('Summer Dress', 'Lightweight summer dress for a chic outfit.', 39.99, 'https://example.com/summer-dress.jpg'),
    ('Backpack', 'Durable backpack with multiple compartments.', 49.99, 'https://example.com/backpack.jpg'),
    ('Wristwatch', 'Elegant wristwatch for both formal and casual occasions.', 199.99, 'https://example.com/wristwatch.jpg'),
    ('Sun Hat', 'Wide-brimmed sun hat for sun protection.', 29.99, 'https://example.com/sun-hat.jpg'),
    ('Cookware Set', 'Non-stick cookware set for everyday cooking.', 149.99, 'https://example.com/cookware.jpg'),
    ('Blender', 'Powerful blender for making smoothies and sauces.', 79.99, 'https://example.com/blender.jpg'),
    ('Coffee Maker', 'Drip coffee maker for brewing delicious coffee.', 59.99, 'https://example.com/coffee-maker.jpg'),
    ('Electric Kettle', 'Fast electric kettle for boiling water.', 39.99, 'https://example.com/electric-kettle.jpg'),
    ('Kitchen Knife Set', 'High-quality knife set for culinary enthusiasts.', 89.99, 'https://example.com/knife-set.jpg'),
    ('Camping Tent', 'Spacious camping tent for outdoor adventures.', 199.99, 'https://example.com/camping-tent.jpg'),
    ('Sleeping Bag', 'Lightweight sleeping bag for camping and hiking.', 79.99, 'https://example.com/sleeping-bag.jpg'),
    ('Hiking Boots', 'Sturdy hiking boots for rugged terrains.', 129.99, 'https://example.com/hiking-boots.jpg'),
    ('Yoga Mat', 'Eco-friendly yoga mat for comfortable workouts.', 29.99, 'https://example.com/yoga-mat.jpg'),
    ('Dumbbell Set', 'Adjustable dumbbell set for home workouts.', 119.99, 'https://example.com/dumbbell-set.jpg'),
    ('Resistance Bands', 'Set of resistance bands for strength training.', 39.99, 'https://example.com/resistance-bands.jpg'),
    ('Soccer Ball', 'Durable soccer ball for recreational play.', 19.99, 'https://example.com/soccer-ball.jpg'),
    ('Basketball', 'Official size basketball for indoor and outdoor use.', 29.99, 'https://example.com/basketball.jpg'),
    ('Golf Clubs Set', 'Complete set of golf clubs for golf enthusiasts.', 299.99, 'https://example.com/golf-clubs.jpg'),
    ('Tennis Racket', 'High-performance tennis racket for competitive play.', 89.99, 'https://example.com/tennis-racket.jpg'),
    ('Yoga Block', 'Yoga block for providing support during yoga poses.', 12.99, 'https://example.com/yoga-block.jpg'),
    ('First Aid Kit', 'Comprehensive first aid kit for emergencies.', 29.99, 'https://example.com/first-aid-kit.jpg'),
    ('Handheld Vacuum', 'Portable handheld vacuum for quick clean-ups.', 49.99, 'https://example.com/handheld-vacuum.jpg'),
    ('Wireless Earphones', 'True wireless earphones with long battery life.', 69.99, 'https://example.com/wireless-earphones.jpg'),
    ('USB-C Cable', 'Fast-charging USB-C cable for various devices.', 9.99, 'https://example.com/usb-c-cable.jpg'),
    ('External Monitor', 'Slim external monitor for improved productivity.', 199.99, 'https://example.com/external-monitor.jpg')